import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { GetServerSidePropsContext } from 'next';
import { UAParser } from 'ua-parser-js';
import { getDatabaseConnection } from '@/lib/getDBConnection';

type Props = {
  browser: {
    name: string;
    version: string;
    major: string;
  };
};

export default function Home(props: Props) {
  const { browser } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>This is MAIN PAGE</h1>
        <h1>request from browse: {browser.name}</h1>
        <Link href={'/posts/'}>Posts Index Page </Link>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const connection = await getDatabaseConnection();

  const ua = context.req.headers['user-agent'];
  const parser = new UAParser(ua);
  let parserResult = parser.getResult();

  return {
    props: {
      browser: parserResult.browser,
    },
  };
}
